all:
	cd ./iomod && $(MAKE) standalone
	cd ./timemod && $(MAKE) standalone
	cd ./filemod && $(MAKE) standalone
clean:
	cd ./iomod && $(MAKE) clean
	cd ./timemod && $(MAKE) clean
	cd ./filemod && $(MAKE) clean
