all:
	cd ./iomod && $(MAKE) standalone
	cd ./timemod && $(MAKE) standalone
	cd ./filemod && $(MAKE) standalone
	cd ./sqldrivers/mysqlmod && $(MAKE) standalone
	cd ./mathmod && $(MAKE) standalone
	cd ./sessionmod && $(MAKE) standalone
	cd ./networkmod && $(MAKE) standalone
	cd ./processmod && $(MAKE) standalone

clean:
	cd ./iomod && $(MAKE) clean
	cd ./timemod && $(MAKE) clean
	cd ./filemod && $(MAKE) clean
	cd ./sqldrivers/mysqlmod && $(MAKE) clean
	cd ./mathmod && $(MAKE) clean
	cd ./sessionmod && $(MAKE) clean
	cd ./networkmod && $(MAKE) clean
	cd ./processmod && $(MAKE) clean


