#ifndef STATICS_H
#define STATICS_H
static const char* MARBLE_OPEN_TAG = "<marble>";
static const char* MARBLE_CLOSING_TAG = "</marble>";
enum
{
    TOKEN_TYPE_NUMBER,
    TOKEN_TYPE_OPERATOR,
    TOKEN_TYPE_STRING,
    TOKEN_TYPE_IDENTIFIER,
    TOKEN_TYPE_KEYWORD,
    TOKEN_TYPE_SYMBOL
};

enum
{
    NODE_TYPE_VARIABLE_DECLARATION,
    NODE_TYPE_EXPRESSION,
    NODE_TYPE_LITERAL,
    NODE_TYPE_IDENTIFIER,
    NODE_TYPE_STRING,
    NODE_TYPE_KEYWORD,
    NODE_TYPE_FUNCTION_CALL,
    NODE_TYPE_NEGATIVE,
    NODE_TYPE_IF_STMT,
    NODE_TYPE_BODY
};

enum
{
    VARIABLE_TYPE_NUMBER,
    VARIABLE_TYPE_STRING,
    VARIABLE_TYPE_OBJECT
};

enum
{
    VALUE_TYPE_NUMBER,
    VALUE_TYPE_STRING,
    VALUE_TYPE_OBJECT
};


enum
{
    LEFT_TO_RIGHT,
    RIGHT_TO_LEFT,
    NON_ASSOCIATIVE
};


// For the lexer
enum
{
    IS_CHARACTER,
    IS_NUMBER,
    IS_OPERATOR,
    IS_SYMBOL,
    IS_WHITESPACE
};

typedef int TOKEN_TYPE;
typedef int NODE_TYPE;
typedef int VALUE_TYPE;
#endif
